# Agrobiodiversidad

In [6]:
import pandas as pd

# Cargar el archivo CSV en un DataFrame
file_path = '/content/sample_data/AGROBIODIVERSIDAD_cleaned.csv'
df_Agrobiodiversidad = pd.read_csv(file_path)

# Mostrar las primeras filas del DataFrame para verificar
df_Agrobiodiversidad

         ID         CULTVRNAME       LAT      LONG  SPP2
0      6121              Curua  -6.45000 -78.52000  Papa
1      6122  Celendina Pintada  -6.53000 -78.58000  Papa
2      6123     Kello Huaccoto -13.47000 -72.25000  Papa
3      6124    Ccohui Sohuillu -13.47000 -72.25000  Papa
4      6127       Yurac Charca -13.47000 -72.25000  Papa
...     ...                ...       ...       ...   ...
6007  14875      Trompa de cuy  -4.90904 -79.83394  Papa
6008  14876        Conga negra  -4.90904 -79.83394  Papa
6009  14877     Trompa de toro  -4.90904 -79.83394  Papa
6010  14878            Trushca  -4.90904 -79.83394  Papa
6011  14879     Trozo de coche  -4.90904 -79.83394  Papa

[6012 rows x 5 columns]

In [7]:
# 3. Resumen general del DataFrame
print("\n------------------------InformaciÃ³n general del DataFrame:------------------------")
df_Agrobiodiversidad.info()

# 7. Contar valores nulos por columna
print("\n------------------------Conteo de valores nulos y ceros:------------------------")
print((df_Agrobiodiversidad.isnull() | (df_Agrobiodiversidad == 0)).sum())

# 10. Contar frecuencia de valores en una columna (reemplazar 'COLUMNA' por el nombre de una columna)
print("\n------------------------Frecuencia de valores en una columna especÃ­fica:------------------------")
print(df_Agrobiodiversidad['CULTVRNAME'].value_counts() if 'CULTVRNAME' in df_Agrobiodiversidad.columns else "La columna especificada no existe.")

------------------------InformaciÃ³n general del DataFrame:------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6012 entries, 0 to 6011
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          6012 non-null   int64
 1   CULTVRNAME  6011 non-null   object
 2   LAT         6012 non-null   float64
 3   LONG        6012 non-null   float64
 4   SPP2        6012 non-null   object
dtypes: float64(2), int64(1), object(2)
memory usage: 235.0+ KB

------------------------Conteo de valores nulos y ceros:------------------------
ID            0
CULTVRNAME    1
LAT           0
LONG          0
SPP2          0
dtype: int64

------------------------Frecuencia de valores en una columna especÃ­fica:------------------------
CULTVRNAME
Milagro             15
Manzana             15
Huayro              13
Chaucha             12
Amarilla            10
                    ..
Chiquina             1
Clavel Huaita        1
Runtus Puca -awi     1
Capucho              1
Trozo de coche       1
Name: count, Length: 4927, dtype: int64

# Concentracion de Especies (SHP?)

In [3]:
import pandas as pd

# Cargar el archivo CSV en un DataFrame
file_path = '/content/sample_data/Concentracion_espcies_SHP.csv'
df = pd.read_csv(file_path)

# Mostrar las primeras filas del DataFrame para verificar
df

,NOMBDEP,NOMBPROV,NOMBDIST,AREA,CATEGORIA,FUENTE,Sp1_Den,Sp1_Pot,Sp1_Res,Sp3_Den,...,Sp8_Pot,Sp8_Res,Sp9_Den,Sp9_Pot,Sp9_Res,TOT_ESP_GE,TOT_ESP_RE,TOT_POND,Shape_Leng,Shape_Area
0,AMAZONAS,CHACHAPOYAS,BALSAS,2257.488871,Agricola,Interpretado de imÃ¡genes Sentinel 2B - 2017-20...,0,0,0,0,...,0,1,1,1,3,3.0,1.0,5,3.024298,0.001843
1,AMAZONAS,LUYA,PROVIDENCIA,3038.075388,Agricola,Interpretado de imÃ¡genes Sentinel 2B - 2017-20...,0,0,0,0,...,1,2,0,0,0,2.0,1.0,3,2.384072,0.002479
2,AMAZONAS,LUYA,COLCAMAR,2176.425518,Agricola,Interpretado de imÃ¡genes Sentinel 2B - 2017-20...,0,0,0,0,...,0,0,0,0,0,1.0,1.0,2,1.055227,0.001775
3,AMAZONAS,RODRIGUEZ DE MENDOZA,COCHAMAL,3343.880873,Agricola,Interpretado de imÃ¡genes Sentinel 2B - 2017-20...,0,0,0,0,...,0,0,0,0,0,1.0,1.0,2,3.965382,0.002726
4,AMAZONAS,LUYA,PISUQUIA,5323.935964,Agricola,Interpretado de imÃ¡genes Sentinel 2B - 2017-20...,0,0,0,0,...,1,2,0,1,2,3.0,1.0,4,4.834622,0.004344
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
136387,UCAYALI,ATALAYA,TAHUANIA,27340.130279,Agricola,Interpretado de imÃ¡genes Sentinel 2B - 2017-20...,0,0,0,0,...,0,0,0,0,0,0.0,0.0,0,19.253136,0.022554
136388,UCAYALI,CORONEL PORTILLO,CALLERIA,44005.591680,Agricola,Interpretado de imÃ¡genes Sentinel 2B - 2017-20...,0,0,0,0,...,0,0,0,0,0,0.0,0.0,0,21.249833,0.036142
136389,UCAYALI,CORONEL PORTILLO,YARINACOCHA,23971.835606,Agricola,Interpretado de imÃ¡genes Sentinel 2B - 2017-20...,0,0,0,0,...,0,0,0,0,0,0.0,0.0,0,12.766209,0.019690
136390,UCAYALI,PURUS,PURUS,13428.854942,Agricola,Interpretado de imÃ¡genes Sentinel 2B - 2017-20...,0,0,0,0,...,0,0,0,0,0,0.0,0.0,0,9.636639,0.011024
136391,UCAYALI,CORONEL PORTILLO,MANANTAY,8939.354401,Agricola,Interpretado de imÃ¡genes Sentinel 2B - 2017-20...,0,0,0,0,...,0,0,0,0,0,0.0,0.0,0,6.427304,0.007347

# Filtrado del peru sun nulos

In [8]:
import pandas as pd

# Cargar el archivo CSV en un DataFrame
file_path = '/content/sample_data/filtrado_peru_sin_NN.csv'
df_filtrado_sinNull = pd.read_csv(file_path)

# Mostrar las primeras filas del DataFrame para verificar
df_filtrado_sinNull

,Especie,Subsp,Especie_Su,Nombre_com,Departamen,Provincia,Distrito,Longitud,Latitud,Altitud
0,Solanum stenotomum,subsp. stenotomum,Solanum stenotomum subsp. Stenotomum,Pusho,PASCO,PASCO,TICLACAYAN,-76.163333,-10.533611,3545.0
1,Solanum stenotomum,subsp. stenotomum,Solanum stenotomum subsp. Stenotomum,ChapiÃ±a,APURIMAC,COTABAMBAS,MARA,-72.108056,-14.085278,3788.0
2,Solanum stenotomum,subsp. stenotomum,Solanum stenotomum subsp. Stenotomum,TuruÃ±a,CUSCO,PAUCARTAMBO,KOSÃ‘IPATA,-71.376389,-13.041111,1059.0
3,Solanum phureja Juz. et Buk.,NaN,Solanum phureja,Chaucha,PUNO,SANDIA,CUYOCUYO,-69.537222,-14.471389,3427.0
4,Solanum phureja Juz. et Buk.,NaN,Solanum phureja,Chaucha Roja,HUANUCO,HUANUCO,CHINCHAO,-76.066667,-9.633333,1545.0
...,...,...,...,...,...,...,...,...,...,...
1885,Solanum stenotomum,subsp. stenotomum,Solanum stenotomum subsp. Stenotomum,Wacapa Huajran,HUANCAVELICA,TAYACAJA,QUISHUAR,-74.750000,-12.250000,2460.0
1886,Solanum chaucha Juz. et Buk.,NaN,Solanum chaucha,Yana PiÃ±a,HUANCAVELICA,TAYACAJA,PAZOS,-75.071389,-12.259167,3810.0
1887,Solanum chaucha Juz. et Buk.,NaN,Solanum chaucha,Yana PiÃ±a,HUANCAVELICA,TAYACAJA,QUISHUAR,-74.750000,-12.250000,2460.0
1888,Solanum chaucha Juz. et Buk.,NaN,Solanum chaucha,Yana Tarma,HUANCAVELICA,TAYACAJA,PAZOS,-75.071389,-12.259167,3810.0
1889,Solanum chaucha Juz. et Buk.,NaN,Solanum chaucha,Yana Tarma,HUANCAVELICA,TAYACAJA,QUISHUAR,-74.750000,-12.250000,2460.0

In [9]:
# 3. Resumen general del DataFrame
print("\n------------------------InformaciÃ³n general del DataFrame:------------------------")
df_filtrado_sinNull.info()

# 7. Contar valores nulos por columna
print("\n------------------------Conteo de valores nulos y ceros:------------------------")
print((df_filtrado_sinNull.isnull() | (df_filtrado_sinNull == 0)).sum())

# 10. Contar frecuencia de valores en una columna (reemplazar 'COLUMNA' por el nombre de una columna)
print("\n------------------------Frecuencia de valores en una columna especÃ­fica:------------------------")
print(df_filtrado_sinNull['Nombre_com'].value_counts() if 'Nombre_com' in df_filtrado_sinNull.columns else "La columna especificada no existe.")

------------------------InformaciÃ³n general del DataFrame:------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1890 entries, 0 to 1889
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Especie     1890 non-null   object
 1   Subsp       1222 non-null   object
 2   Especie_Su  1890 non-null   object
 3   Nombre_com  1890 non-null   object
 4   Departamen  1890 non-null   object
 5   Provincia   1890 non-null   object
 6   Distrito    1890 non-null   object
 7   Longitud    1890 non-null   float64
 8   Latitud     1890 non-null   float64
 9   Altitud     1890 non-null   float64
dtypes: float64(3), object(7)
memory usage: 147.8+ KB

------------------------Conteo de valores nulos y ceros:------------------------
Especie         0
Subsp         668
Especie_Su      0
Nombre_com      0
Departamen      0
Provincia       0
Distrito        0
Longitud        0
Latitud         0
Altitud         0
dtype: int64

------------------------Frecuencia de valores en una columna especÃ­fica:------------------------
Nombre_com
Chaucha             41
Puka mama           28
Wayro               25
Amarilla            20
Chaucha Amarilla    19
                    ..
Achanjaira           1
Hawicho              1
LimeÃ±a Amarilla      1
LimeÃ±a amarilla      1
Pusho                1
Name: count, Length: 965, dtype: int64

# Erosion del suelo

In [ ]:
import pandas as pd

# Cargar los archivos CSV y agregar la columna 'anio' correspondiente
df_2010 = pd.read_csv("/content/sample_data/2010.csv", sep=';')
df_2010['anio'] = 2010

df_2011 = pd.read_csv("/content/sample_data/2011.csv", sep=';')
df_2011['anio'] = 2011

df_2012 = pd.read_csv("/content/sample_data/2012.csv", sep=';')
df_2012['anio'] = 2012

df_2013 = pd.read_csv("/content/sample_data/2013.csv", sep=';')
df_2013['anio'] = 2013

df_2014 = pd.read_csv("/content/sample_data/2014.csv", sep=';')
df_2014['anio'] = 2014

# Revisar el contenido de uno de los DataFrames para verificar
df_2010.info()
df_2011.info()
df_2012.info()
df_2013.info()
df_2014.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12794 entries, 0 to 12793
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   UBIGEO    12794 non-null  int64
 1   NOMBDEP   12794 non-null  object
 2   NOMBPROV  12794 non-null  object
 3   NOMBDIST  12794 non-null  object
 4   rango     12794 non-null  object
 5   anio      12794 non-null  int64
dtypes: int64(2), object(4)
memory usage: 599.8+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12959 entries, 0 to 12958
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   UBIGEO    12959 non-null  int64
 1   NOMBDEP   12959 non-null  object
 2   NOMBPROV  12959 non-null  object
 3   NOMBDIST  12959 non-null  object
 4   rango     12959 non-null  object
 5   anio      12959 non-null  int64
dtypes: int64(2), object(4)
memory usage: 607.6+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13232 entries, 0 to 13231
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   UBIGEO    13232 non-null  int64
 1   NOMBDEP   13232 non-null  object
 2   NOMBPROV  13232 non-null  object
 3   NOMBDIST  13232 non-null  object
 4   rango     13232 non-null  object
 5   anio      13232 non-null  int64
dtypes: int64(2), object(4)
memory usage: 620.4+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13172 entries, 0 to 13171
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   UBIGEO    13172 non-null  int64
 1   NOMBDEP   13172 non-null  object
 2   NOMBPROV  13172 non-null  object
 3   NOMBDIST  13172 non-null  object
 4   rango     13172 non-null  object
 5   anio      13172 non-null  int64
dtypes: int64(2), object(4)
memory usage: 617.6+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9785 entries, 0 to 9784
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   UBIGEO    9785 non-null   int64
 1   NOMBDEP   9785 non-null   object
 2   NOMBPROV  9785 non-null   object
 3   NOMBDIST  9785 non-null   object
 4   rango     9785 non-null   object
 5   anio      9785 non-null   int64
dtypes: int64(2), object(4)
memory usage: 458.8+ KB

In [ ]:
# Concatenar todos los DataFrames
df_combinado = pd.concat([df_2010, df_2011, df_2012, df_2013, df_2014], ignore_index=True)

# Verificar las primeras filas del DataFrame combinado
df_combinado.head()

# Comprobar si las columnas estÃ¡n correctamente alineadas
df_combinado.columns

Index(['UBIGEO', 'NOMBDEP', 'NOMBPROV', 'NOMBDIST', 'rango', 'anio'], dtype='object')

In [ ]:
# Crear la tabla pivote con aÃ±os como columnas
df_pivot = df_combinado.pivot_table(
    index=['NOMBDEP', 'NOMBPROV', 'NOMBDIST'],  # Index en base a P.E
    columns='anio',                                       # AÃ±o como columnas
    values='rango',                                       # Valor a mostrar en celdas
    aggfunc='first'                                       # Si hay duplicados, tomar el primero
).reset_index()

# Revisar las primeras filas de la tabla pivote
df_pivot.head()

anio,NOMBDEP,NOMBPROV,NOMBDIST,2010,2011,2012,2013,2014
0,AMAZONAS,BAGUA,ARAMANGO,0 - 0.01,0 - 0.01,0 - 0.01,0 - 0.01,0.01 - 0.50
1,AMAZONAS,BAGUA,BAGUA,0 - 0.01,0 - 0.01,0 - 0.01,0 - 0.01,1.0 - 10
2,AMAZONAS,BAGUA,COPALLIN,0.01 - 0.50,0.01 - 0.50,0.01 - 0.50,0.01 - 0.50,0.50 - 1.0
3,AMAZONAS,BAGUA,EL PARCO,0.01 - 0.50,0.01 - 0.50,0.01 - 0.50,0.01 - 0.50,1.0 - 10
4,AMAZONAS,BAGUA,IMAZA,0 - 0.01,0 - 0.01,0 - 0.01,0 - 0.01,0 - 0.01

In [ ]:
# 1. Ver las primeras 5 filas
print("------------------------Primeras 5 filas:------------------------")
print(df_pivot.head())

# 3. Resumen general del DataFrame
print("\n------------------------InformaciÃ³n general del DataFrame:------------------------")
df_pivot.info()

# 7. Contar valores nulos por columna
print("\n------------------------Conteo de valores nulos y ceros:------------------------")
print((df_pivot.isnull() | (df_pivot == 0)).sum())
# 10. Contar frecuencia de valores en una columna (reemplazar 'COLUMNA' por el nombre de una columna)
print("\n------------------------Frecuencia de valores en una columna especÃ­fica:------------------------")
# print(df_pivot['PRODUCTO'].value_counts() if 'PRODUCTO' in df_pivot.columns else "La columna especificada no existe.")

------------------------Primeras 5 filas:------------------------
anio   NOMBDEP NOMBPROV  NOMBDIST         2010         2011         2012  \
0     AMAZONAS    BAGUA  ARAMANGO     0 - 0.01     0 - 0.01     0 - 0.01
1     AMAZONAS    BAGUA     BAGUA     0 - 0.01     0 - 0.01     0 - 0.01
2     AMAZONAS    BAGUA  COPALLIN  0.01 - 0.50  0.01 - 0.50  0.01 - 0.50
3     AMAZONAS    BAGUA  EL PARCO  0.01 - 0.50  0.01 - 0.50  0.01 - 0.50
4     AMAZONAS    BAGUA     IMAZA     0 - 0.01     0 - 0.01     0 - 0.01

anio         2013         2014
0        0 - 0.01  0.01 - 0.50
1        0 - 0.01     1.0 - 10
2     0.01 - 0.50   0.50 - 1.0
3     0.01 - 0.50     1.0 - 10
4        0 - 0.01     0 - 0.01

------------------------InformaciÃ³n general del DataFrame:------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1874 entries, 0 to 1873
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   NOMBDEP   1874 non-null   object
 1   NOMBPROV  1874 non-null   object
 2   NOMBDIST  1874 non-null   object
 3   2010      1874 non-null   object
 4   2011      1874 non-null   object
 5   2012      1874 non-null   object
 6   2013      1874 non-null   object
 7   2014      1874 non-null   object
dtypes: object(8)
memory usage: 117.2+ KB

------------------------Conteo de valores nulos y ceros:------------------------
anio
NOMBDEP     0
NOMBPROV    0
NOMBDIST    0
2010        0
2011        0
2012        0
2013        0
2014        0
dtype: int64

------------------------Frecuencia de valores en una columna especÃ­fica:------------------------

# Nevadas

In [6]:
import pandas as pd

# Lista de nombres de los meses
meses = ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre']
ruta_base = '/content/sample_data/'

# Crear un diccionario para almacenar los DataFrames
dataframes_meses = {}

# Cargar cada archivo en un DataFrame
for mes in meses:
    archivo = f"{ruta_base}{mes}.csv"
    df = pd.read_csv(archivo, delimiter=';')

    # Eliminar columnas sin nombre
    df = df.loc[:, ~df.columns.str.contains('^Unnamed')]

    # Guardar en el diccionario
    dataframes_meses[mes] = df

# Verificar los DataFrames cargados
for mes, df in dataframes_meses.items():
    print(f"Datos del mes de {mes}:")
    print(df.head(), "\n")

Datos del mes de Enero:
   UBIGEO      NOMBDEP   NOMBPROV           NOMBDIST frecuencia
0  130104  LA LIBERTAD   TRUJILLO          HUANCHACO      0 - 0
1  130207  LA LIBERTAD     ASCOPE    SANTIAGO DE CAO      0 - 0
2  130204  LA LIBERTAD     ASCOPE   MAGDALENA DE CAO      0 - 0
3  130206  LA LIBERTAD     ASCOPE             RAZURI      0 - 0
4  130701  LA LIBERTAD  PACASMAYO  SAN PEDRO DE LLOC      0 - 0

Datos del mes de Febrero:
   UBIGEO      NOMBDEP   NOMBPROV           NOMBDIST frecuencia
0  130104  LA LIBERTAD   TRUJILLO          HUANCHACO      0 - 0
1  130207  LA LIBERTAD     ASCOPE    SANTIAGO DE CAO      0 - 0
2  130204  LA LIBERTAD     ASCOPE   MAGDALENA DE CAO      0 - 0
3  130206  LA LIBERTAD     ASCOPE             RAZURI      0 - 0
4  130701  LA LIBERTAD  PACASMAYO  SAN PEDRO DE LLOC      0 - 0

Datos del mes de Marzo:
   UBIGEO      NOMBDEP   NOMBPROV           NOMBDIST frecuencia
0  130104  LA LIBERTAD   TRUJILLO          HUANCHACO      0 - 0
1  130207  LA LIBERTAD     ASCOPE    SANTIAGO DE CAO      0 - 0
2  130204  LA LIBERTAD     ASCOPE   MAGDALENA DE CAO      0 - 0
3  130206  LA LIBERTAD     ASCOPE             RAZURI      0 - 0
4  130701  LA LIBERTAD  PACASMAYO  SAN PEDRO DE LLOC      0 - 0

Datos del mes de Abril:
   UBIGEO   NOMBDEP      NOMBPROV      NOMBDIST frecuencia
0   10205  AMAZONAS         BAGUA         IMAZA      0 - 0
1   10402  AMAZONAS  CONDORCANQUI     EL CENEPA      0 - 0
2   10403  AMAZONAS  CONDORCANQUI  RIO SANTIAGO      0 - 0
3   10103  AMAZONAS   CHACHAPOYAS        BALSAS      0 - 0
4   10515  AMAZONAS          LUYA   PROVIDENCIA      0 - 0

Datos del mes de Mayo:
   UBIGEO      NOMBDEP   NOMBPROV           NOMBDIST frecuencia
0  130104  LA LIBERTAD   TRUJILLO          HUANCHACO      0 - 0
1  130207  LA LIBERTAD     ASCOPE    SANTIAGO DE CAO      0 - 0
2  130204  LA LIBERTAD     ASCOPE   MAGDALENA DE CAO      0 - 0
3  130206  LA LIBERTAD     ASCOPE             RAZURI      0 - 0
4  130701  LA LIBERTAD  PACASMAYO  SAN PEDRO DE LLOC      0 - 0

Datos del mes de Junio:
   UBIGEO      NOMBDEP   NOMBPROV           NOMBDIST frecuencia
0  130104  LA LIBERTAD   TRUJILLO          HUANCHACO      0 - 0
1  130207  LA LIBERTAD     ASCOPE    SANTIAGO DE CAO      0 - 0
2  130204  LA LIBERTAD     ASCOPE   MAGDALENA DE CAO      0 - 0
3  130206  LA LIBERTAD     ASCOPE             RAZURI      0 - 0
4  130701  LA LIBERTAD  PACASMAYO  SAN PEDRO DE LLOC      0 - 0

Datos del mes de Julio:
   UBIGEO      NOMBDEP   NOMBPROV           NOMBDIST frecuencia
0  130104  LA LIBERTAD   TRUJILLO          HUANCHACO      0 - 0
1  130207  LA LIBERTAD     ASCOPE    SANTIAGO DE CAO      0 - 0
2  130204  LA LIBERTAD     ASCOPE   MAGDALENA DE CAO      0 - 0
3  130206  LA LIBERTAD     ASCOPE             RAZURI      0 - 0
4  130701  LA LIBERTAD  PACASMAYO  SAN PEDRO DE LLOC      0 - 0

Datos del mes de Agosto:
   UBIGEO      NOMBDEP   NOMBPROV           NOMBDIST frecuencia
0  130104  LA LIBERTAD   TRUJILLO          HUANCHACO      0 - 0
1  130207  LA LIBERTAD     ASCOPE    SANTIAGO DE CAO      0 - 0
2  130204  LA LIBERTAD     ASCOPE   MAGDALENA DE CAO      0 - 0
3  130206  LA LIBERTAD     ASCOPE             RAZURI      0 - 0
4  130701  LA LIBERTAD  PACASMAYO  SAN PEDRO DE LLOC      0 - 0

Datos del mes de Septiembre:
   UBIGEO   NOMBDEP   NOMBPROV                 NOMBDIST frecuencia
0   30101  APURIMAC    ABANCAY                  ABANCAY      2 - 5
1   30101  APURIMAC    ABANCAY                  ABANCAY      2 - 5
2   30101  APURIMAC    ABANCAY                  ABANCAY      0 - 0
3   20502    ANCASH  BOLOGNESI  ABELARDO PARDO LEZAMETA      0 - 0
4   40302  AREQUIPA   CARAVELI                    ACARI      0 - 0

Datos del mes de Octubre:
   UBIGEO      NOMBDEP   NOMBPROV           NOMBDIST frecuencia
0  130104  LA LIBERTAD   TRUJILLO          HUANCHACO      0 - 0
1  130207  LA LIBERTAD     ASCOPE    SANTIAGO DE CAO      0 - 0
2  130204  LA LIBERTAD     ASCOPE   MAGDALENA DE CAO      0 - 0
3  130206  LA LIBERTAD     ASCOPE             RAZURI      0 - 0
4  130701  LA LIBERTAD  PACASMAYO  SAN PEDRO DE LLOC      0 - 0

Datos del mes de Noviembre:
   UBIGEO      NOMBDEP   NOMBPROV           NOMBDIST frecuencia
0  130104  LA LIBERTAD   TRUJILLO          HUANCHACO      0 - 0
1  130207  LA LIBERTAD     ASCOPE    SANTIAGO DE CAO      0 - 0
2  130204  LA LIBERTAD     ASCOPE   MAGDALENA DE CAO      0 - 0
3  130206  LA LIBERTAD     ASCOPE             RAZURI      0 - 0
4  130701  LA LIBERTAD  PACASMAYO  SAN PEDRO DE LLOC      0 - 0

Datos del mes de Diciembre:
   UBIGEO      NOMBDEP   NOMBPROV           NOMBDIST frecuencia
0  130104  LA LIBERTAD   TRUJILLO          HUANCHACO      0 - 0
1  130207  LA LIBERTAD     ASCOPE    SANTIAGO DE CAO      0 - 0
2  130204  LA LIBERTAD     ASCOPE   MAGDALENA DE CAO      0 - 0
3  130206  LA LIBERTAD     ASCOPE             RAZURI      0 - 0
4  130701  LA LIBERTAD  PACASMAYO  SAN PEDRO DE LLOC      0 - 0

In [7]:
# Verificar si un P.E tiene el mismo UBIGEO en cualquiera de las tablas
def verificar_pe_ubigeo(dataframes):
    ubigeo_diferente = []
    for mes1, df1 in dataframes.items():
        for mes2, df2 in dataframes.items():
            if mes1 != mes2:
                merged = pd.merge(df1, df2, on=['NOMBDEP', 'NOMBPROV', 'NOMBDIST'], suffixes=(f'_{mes1}', f'_{mes2}'))
                diferentes = merged[merged['UBIGEO_' + mes1] != merged['UBIGEO_' + mes2]]
                if not diferentes.empty:
                    ubigeo_diferente.append((mes1, mes2, diferentes))
    return ubigeo_diferente

# Frecuencia de valores Ãºnicos de cada columna en dos meses cualesquiera
def frecuencia_columnas(df1, df2, mes1, mes2):
    print(f"Frecuencia de valores Ãºnicos para el mes de {mes1}:")
    for col in df1.columns:
        print(f"Columna {col}:")
        print(df1[col].value_counts(), "\n")

    print(f"Frecuencia de valores Ãºnicos para el mes de {mes2}:")
    for col in df2.columns:
        print(f"Columna {col}:")
        print(df2[col].value_counts(), "\n")

# InformaciÃ³n resumen por tabla
def resumen_tablas(dataframes):
    resumen = []
    for mes, df in dataframes.items():
        total_filas = len(df)
        clases_ubigeo = df['UBIGEO'].nunique()
        repeticiones_pe = df.duplicated(subset=['NOMBDEP', 'NOMBPROV', 'NOMBDIST']).sum()

        resumen.append({
            'Mes': mes,
            'Total Filas': total_filas,
            'Clases UBIGEO': clases_ubigeo,
            'Repeticiones P.E.': repeticiones_pe
        })
    return pd.DataFrame(resumen)

# EjecuciÃ³n de las funciones
# VerificaciÃ³n de UBIGEO diferente entre tablas
resultados_ubigeo = verificar_pe_ubigeo(dataframes_meses)
if resultados_ubigeo:
    for mes1, mes2, diferentes in resultados_ubigeo:
        print(f"Diferencias de UBIGEO entre {mes1} y {mes2}:")
        print(diferentes)

# Frecuencia de valores Ãºnicos para dos meses especÃ­ficos
mes_a, mes_b = 'Enero', 'Febrero'  # Cambia segÃºn los meses que quieras comparar
frecuencia_columnas(dataframes_meses[mes_a], dataframes_meses[mes_b], mes_a, mes_b)

# Resumen de cada tabla
resumen = resumen_tablas(dataframes_meses)
resumen

Frecuencia de valores Ãºnicos para el mes de Enero:
Columna UBIGEO:
UBIGEO
80602     10
151028     9
151021     9
40608      8
50703      7
          ..
220101     1
10517      1
160302     1
160703     1
200802     1
Name: count, Length: 1874, dtype: int64

Columna NOMBDEP:
NOMBDEP
LIMA             297
AREQUIPA         257
PUNO             203
AYACUCHO         194
ANCASH           176
HUANCAVELICA     170
JUNIN            166
CUSCO            143
CAJAMARCA        135
LA LIBERTAD       98
HUANUCO           91
AMAZONAS          89
APURIMAC          89
PIURA             81
SAN MARTIN        77
LORETO            67
ICA               62
PASCO             51
LAMBAYEQUE        48
MOQUEGUA          39
TACNA             36
TUMBES            24
UCAYALI           22
MADRE DE DIOS     16
CALLAO            11
Name: count, dtype: int64

Columna NOMBPROV:
NOMBPROV
YAUYOS                       77
CAYLLOMA                     65
LIMA                         58
LUCANAS                      49
HUAROCHIRI                   49
                             ..
CAJABAMBA                     4
CARLOS FERMIN FITZCARRALD     3
PURUS                         3
HUALGAYOC                     3
ASUNCION                      2
Name: count, Length: 196, dtype: int64

Columna NOMBDIST:
NOMBDIST
SANTA ROSA          15
MIRAFLORES          14
CHECACUPE           10
TANTA                9
SANTA LUCIA          9
                    ..
NIEVA                1
YAMON                1
POSIC                1
SAN CARLOS           1
CRISTO NOS VALGA     1
Name: count, Length: 1722, dtype: int64

Columna frecuencia:
frecuencia
0 - 0      2051
2 - 5       386
5 - 10      138
10 - 15      41
15 - 20      15
20 - 25       7
25 - 31       4
Name: count, dtype: int64

Frecuencia de valores Ãºnicos para el mes de Febrero:
Columna UBIGEO:
UBIGEO
40601     7
40602     7
40504     6
80602     6
90607     6
         ..
200803    1
200304    1
200806    1
200804    1
200110    1
Name: count, Length: 1874, dtype: int64

Columna NOMBDEP:
NOMBDEP
LIMA             250
AREQUIPA         224
PUNO             200
ANCASH           176
HUANCAVELICA     162
AYACUCHO         159
JUNIN            150
CUSCO            136
CAJAMARCA        133
LA LIBERTAD       98
AMAZONAS          89
HUANUCO           88
APURIMAC          87
PIURA             81
SAN MARTIN        77
LORETO            67
ICA               62
LAMBAYEQUE        48
PASCO             40
MOQUEGUA          36
TACNA             35
TUMBES            24
UCAYALI           22
MADRE DE DIOS     16
CALLAO            11
Name: count, dtype: int64

Columna NOMBPROV:
NOMBPROV
LIMA                         58
CAYLLOMA                     50
YAUYOS                       46
HUAROCHIRI                   46
AREQUIPA                     43
                             ..
POMABAMBA                     4
PURUS                         3
HUALGAYOC                     3
CARLOS FERMIN FITZCARRALD     3
ASUNCION                      2
Name: count, Length: 196, dtype: int64

Columna NOMBDIST:
NOMBDIST
SANTA ROSA      15
CHUQUIBAMBA      8
PALCA            8
SAN ANTONIO      7
ANDARAY          7
                ..
SOCOS            1
TAMBILLO         1
CAYARA           1
HUANCARAYLLA     1
SAURAMA          1
Name: count, Length: 1722, dtype: int64

Columna frecuencia:
frecuencia
0 - 0      2026
2 - 5       299
5 - 10       99
10 - 15      31
15 - 20       8
20 - 25       6
25 - 31       2
Name: count, dtype: int64

           Mes  Total Filas  Clases UBIGEO  Repeticiones P.E.
0        Enero         2642           1874                768
1      Febrero         2471           1874                597
2        Marzo         2581           1874                707
3        Abril         3256           1874               1382
4         Mayo         4640           1874               2766
5        Junio         5410           1874               3536
6        Julio         4977           1874               3103
7       Agosto         5047           1874               3173
8   Septiembre         4263           1874               2389
9      Octubre         3625           1874               1751
10   Noviembre         3322           1874               1448
11   Diciembre         2861           1874                987

In [8]:
# Encontrar la cantidad de UBIGEOs que se repiten en todas las tablas
def ubigeos_repetidos_en_todas(dataframes):
    # Extraer los UBIGEOs de cada DataFrame como conjuntos
    conjuntos_ubigeos = [set(df['UBIGEO']) for df in dataframes.values()]
    # Encontrar la intersecciÃ³n de todos los conjuntos
    ubigeos_comunes = set.intersection(*conjuntos_ubigeos)
    return len(ubigeos_comunes)

# Calcular y mostrar el nÃºmero de UBIGEOs repetidos en todas las tablas
cantidad_ubigeos_comunes = ubigeos_repetidos_en_todas(dataframes_meses)
print(f"Cantidad de UBIGEOs que se repiten en todas las tablas: {cantidad_ubigeos_comunes}")

Cantidad de UBIGEOs que se repiten en todas las tablas: 1874

In [9]:
def resumen_repeticiones(df, mes, columna='UBIGEO'):
    # Calcular la frecuencia de repeticiones de los valores Ãºnicos
    conteo_frecuencias = df[columna].value_counts()
    # Contar cuÃ¡ntos valores tienen la misma cantidad de repeticiones
    resumen = conteo_frecuencias.value_counts()

    print(f"Para el mes de {mes}:")
    for repeticiones, cantidad in resumen.items():
        print(f"Hay {cantidad} {columna.lower()}s que se repiten {repeticiones} veces.")

# Ejemplo de uso con el DataFrame del mes de Enero
resumen_repeticiones(dataframes_meses['Enero'], 'Enero', columna='UBIGEO')

Para el mes de Enero:
Hay 1369 ubigeos que se repiten 1 veces.
Hay 361 ubigeos que se repiten 2 veces.
Hay 88 ubigeos que se repiten 3 veces.
Hay 27 ubigeos que se repiten 4 veces.
Hay 14 ubigeos que se repiten 5 veces.
Hay 7 ubigeos que se repiten 7 veces.
Hay 4 ubigeos que se repiten 6 veces.
Hay 2 ubigeos que se repiten 9 veces.
Hay 1 ubigeos que se repiten 10 veces.
Hay 1 ubigeos que se repiten 8 veces.

In [13]:
import re

# FunciÃ³n para extraer rangos de frecuencia de los datos
def obtener_rangos_frecuencia(dataframes):
    rangos = set()
    for df in dataframes.values():
        rangos.update(df['frecuencia'].dropna().unique())  # Ignorar valores nulos

    # Extraer lÃ­mites numÃ©ricos de los rangos usando regex
    rango_valores = {}
    for rango in rangos:
        match = re.match(r'(\d+)\s*-\s*(\d+)', rango)
        if match:
            low, high = map(int, match.groups())
            promedio = (low + high) / 2
            rango_valores[rango] = promedio

    return rango_valores

# FunciÃ³n para consolidar registros duplicados por UBIGEO
def consolidar_frecuencia_por_ubigeo(df, rangos_frecuencia):
    # Mapear la columna 'frecuencia' a valores numÃ©ricos basados en los rangos encontrados
    df['frecuencia_valor'] = df['frecuencia'].map(rangos_frecuencia)

    # Consolidar por UBIGEO
    consolidado = (
        df.groupby(['UBIGEO', 'NOMBDEP', 'NOMBPROV', 'NOMBDIST'], as_index=False)
        .agg({'frecuencia_valor': lambda x: x.mean() if not x.isnull().all() else None})  # Manejo de valores nulos
    )

    # Renombrar la columna consolidada como "frecuencia"
    consolidado.rename(columns={'frecuencia_valor': 'frecuencia'}, inplace=True)

    return consolidado

# Obtener los rangos de frecuencia dinÃ¡micamente de todas las tablas
rangos_frecuencia = obtener_rangos_frecuencia(dataframes_meses)
print("Rangos de frecuencia detectados:", rangos_frecuencia)

# Aplicar la funciÃ³n a cada tabla de los meses
for mes, df in dataframes_meses.items():
    print(f"Consolidando datos para el mes de {mes}...")
    dataframes_meses[mes] = consolidar_frecuencia_por_ubigeo(df, rangos_frecuencia)

# Verificar los resultados
for mes, df in dataframes_meses.items():
    print(f"Datos consolidados del mes de {mes}:")
    print(df.head(), "\n")

Rangos de frecuencia detectados: {'2 - 5': 3.5, '15 - 20': 17.5, '5 - 10': 7.5, '10 - 15': 12.5, '20 - 25': 22.5, '25 - 31': 28.0, '0 - 0': 0.0}
Consolidando datos para el mes de Enero...
Consolidando datos para el mes de Febrero...
Consolidando datos para el mes de Marzo...
Consolidando datos para el mes de Abril...
Consolidando datos para el mes de Mayo...
Consolidando datos para el mes de Junio...
Consolidando datos para el mes de Julio...
Consolidando datos para el mes de Agosto...
Consolidando datos para el mes de Septiembre...
Consolidando datos para el mes de Octubre...
Consolidando datos para el mes de Noviembre...
Consolidando datos para el mes de Diciembre...
Datos consolidados del mes de Enero:
   UBIGEO   NOMBDEP     NOMBPROV     NOMBDIST  frecuencia
0   10101  AMAZONAS  CHACHAPOYAS  CHACHAPOYAS         0.0
1   10102  AMAZONAS  CHACHAPOYAS     ASUNCION         0.0
2   10103  AMAZONAS  CHACHAPOYAS       BALSAS         0.0
3   10104  AMAZONAS  CHACHAPOYAS        CHETO         0.0
4   10105  AMAZONAS  CHACHAPOYAS    CHILIQUIN         0.0

Datos consolidados del mes de Febrero:
   UBIGEO   NOMBDEP     NOMBPROV     NOMBDIST  frecuencia
0   10101  AMAZONAS  CHACHAPOYAS  CHACHAPOYAS         0.0
1   10102  AMAZONAS  CHACHAPOYAS     ASUNCION         0.0
2   10103  AMAZONAS  CHACHAPOYAS       BALSAS         0.0
3   10104  AMAZONAS  CHACHAPOYAS        CHETO         0.0
4   10105  AMAZONAS  CHACHAPOYAS    CHILIQUIN         0.0

Datos consolidados del mes de Marzo:
   UBIGEO   NOMBDEP     NOMBPROV     NOMBDIST  frecuencia
0   10101  AMAZONAS  CHACHAPOYAS  CHACHAPOYAS         0.0
1   10102  AMAZONAS  CHACHAPOYAS     ASUNCION         0.0
2   10103  AMAZONAS  CHACHAPOYAS       BALSAS         0.0
3   10104  AMAZONAS  CHACHAPOYAS        CHETO         0.0
4   10105  AMAZONAS  CHACHAPOYAS    CHILIQUIN         0.0

Datos consolidados del mes de Abril:
   UBIGEO   NOMBDEP     NOMBPROV     NOMBDIST  frecuencia
0   10101  AMAZONAS  CHACHAPOYAS  CHACHAPOYAS         0.0
1   10102  AMAZONAS  CHACHAPOYAS     ASUNCION         0.0
2   10103  AMAZONAS  CHACHAPOYAS       BALSAS         0.0
3   10104  AMAZONAS  CHACHAPOYAS        CHETO         0.0
4   10105  AMAZONAS  CHACHAPOYAS    CHILIQUIN         0.0

Datos consolidados del mes de Mayo:
   UBIGEO   NOMBDEP     NOMBPROV     NOMBDIST  frecuencia
0   10101  AMAZONAS  CHACHAPOYAS  CHACHAPOYAS         0.0
1   10102  AMAZONAS  CHACHAPOYAS     ASUNCION         0.0
2   10103  AMAZONAS  CHACHAPOYAS       BALSAS         3.5
3   10104  AMAZONAS  CHACHAPOYAS        CHETO         0.0
4   10105  AMAZONAS  CHACHAPOYAS    CHILIQUIN         0.0

Datos consolidados del mes de Junio:
   UBIGEO   NOMBDEP     NOMBPROV     NOMBDIST  frecuencia
0   10101  AMAZONAS  CHACHAPOYAS  CHACHAPOYAS         0.0
1   10102  AMAZONAS  CHACHAPOYAS     ASUNCION         0.0
2   10103  AMAZONAS  CHACHAPOYAS       BALSAS         3.5
3   10104  AMAZONAS  CHACHAPOYAS        CHETO         0.0
4   10105  AMAZONAS  CHACHAPOYAS    CHILIQUIN         3.5

Datos consolidados del mes de Julio:
   UBIGEO   NOMBDEP     NOMBPROV     NOMBDIST  frecuencia
0   10101  AMAZONAS  CHACHAPOYAS  CHACHAPOYAS         0.0
1   10102  AMAZONAS  CHACHAPOYAS     ASUNCION         0.0
2   10103  AMAZONAS  CHACHAPOYAS       BALSAS         3.5
3   10104  AMAZONAS  CHACHAPOYAS        CHETO         0.0
4   10105  AMAZONAS  CHACHAPOYAS    CHILIQUIN         3.5

Datos consolidados del mes de Agosto:
   UBIGEO   NOMBDEP     NOMBPROV     NOMBDIST  frecuencia
0   10101  AMAZONAS  CHACHAPOYAS  CHACHAPOYAS         0.0
1   10102  AMAZONAS  CHACHAPOYAS     ASUNCION         0.0
2   10103  AMAZONAS  CHACHAPOYAS       BALSAS         3.5
3   10104  AMAZONAS  CHACHAPOYAS        CHETO         0.0
4   10105  AMAZONAS  CHACHAPOYAS    CHILIQUIN         3.5

Datos consolidados del mes de Septiembre:
   UBIGEO   NOMBDEP     NOMBPROV     NOMBDIST  frecuencia
0   10101  AMAZONAS  CHACHAPOYAS  CHACHAPOYAS         0.0
1   10102  AMAZONAS  CHACHAPOYAS     ASUNCION         0.0
2   10103  AMAZONAS  CHACHAPOYAS       BALSAS         0.0
3   10104  AMAZONAS  CHACHAPOYAS        CHETO         0.0
4   10105  AMAZONAS  CHACHAPOYAS    CHILIQUIN         0.0

Datos consolidados del mes de Octubre:
   UBIGEO   NOMBDEP     NOMBPROV     NOMBDIST  frecuencia
0   10101  AMAZONAS  CHACHAPOYAS  CHACHAPOYAS         0.0
1   10102  AMAZONAS  CHACHAPOYAS     ASUNCION         0.0
2   10103  AMAZONAS  CHACHAPOYAS       BALSAS         0.0
3   10104  AMAZONAS  CHACHAPOYAS        CHETO         0.0
4   10105  AMAZONAS  CHACHAPOYAS    CHILIQUIN         0.0

Datos consolidados del mes de Noviembre:
   UBIGEO   NOMBDEP     NOMBPROV     NOMBDIST  frecuencia
0   10101  AMAZONAS  CHACHAPOYAS  CHACHAPOYAS         0.0
1   10102  AMAZONAS  CHACHAPOYAS     ASUNCION         0.0
2   10103  AMAZONAS  CHACHAPOYAS       BALSAS         0.0
3   10104  AMAZONAS  CHACHAPOYAS        CHETO         0.0
4   10105  AMAZONAS  CHACHAPOYAS    CHILIQUIN         0.0

Datos consolidados del mes de Diciembre:
   UBIGEO   NOMBDEP     NOMBPROV     NOMBDIST  frecuencia
0   10101  AMAZONAS  CHACHAPOYAS  CHACHAPOYAS         0.0
1   10102  AMAZONAS  CHACHAPOYAS     ASUNCION         0.0
2   10103  AMAZONAS  CHACHAPOYAS       BALSAS         0.0
3   10104  AMAZONAS  CHACHAPOYAS        CHETO         0.0
4   10105  AMAZONAS  CHACHAPOYAS    CHILIQUIN         0.0

In [18]:
def consolidar_todas_las_tablas_con_info(dataframes):
    # Crear una lista para almacenar los DataFrames modificados
    dfs = []

    for mes, df in dataframes.items():
        # AÃ±adir una columna con el nombre del mes y la frecuencia
        df_mes = df[['UBIGEO', 'NOMBDEP', 'NOMBPROV', 'NOMBDIST', 'frecuencia']].copy()
        df_mes.rename(columns={'frecuencia': mes}, inplace=True)
        dfs.append(df_mes)

    # Unir todos los DataFrames por UBIGEO y las demÃ¡s columnas clave
    df_consolidado = dfs[0]
    for df_mes in dfs[1:]:
        df_consolidado = pd.merge(df_consolidado, df_mes, on=['UBIGEO', 'NOMBDEP', 'NOMBPROV', 'NOMBDIST'], how='outer')

    return df_consolidado

# Consolidar todas las tablas
df_consolidado = consolidar_todas_las_tablas_con_info(dataframes_meses)

In [21]:
# 1. Ver las primeras 5 filas
print("------------------------Primeras 5 filas:------------------------")
print(df_consolidado.head())

# 3. Resumen general del DataFrame
print("\n------------------------InformaciÃ³n general del DataFrame:------------------------")
df_consolidado.info()

# 7. Contar valores nulos por columna
print("\n------------------------Conteo de valores nulos:------------------------")
print(df_consolidado.isnull().sum())
# 10. Contar frecuencia de valores en una columna (reemplazar 'COLUMNA' por el nombre de una columna)
print("\n------------------------Frecuencia de valores en una columna especÃ­fica:------------------------")
# print(df_consolidado['PRODUCTO'].value_counts() if 'PRODUCTO' in df_consolidado.columns else "La columna especificada no existe.")

------------------------Primeras 5 filas:------------------------
   UBIGEO   NOMBDEP     NOMBPROV     NOMBDIST  Enero  Febrero  Marzo  Abril  \
0   10101  AMAZONAS  CHACHAPOYAS  CHACHAPOYAS    0.0      0.0    0.0    0.0
1   10102  AMAZONAS  CHACHAPOYAS     ASUNCION    0.0      0.0    0.0    0.0
2   10103  AMAZONAS  CHACHAPOYAS       BALSAS    0.0      0.0    0.0    0.0
3   10104  AMAZONAS  CHACHAPOYAS        CHETO    0.0      0.0    0.0    0.0
4   10105  AMAZONAS  CHACHAPOYAS    CHILIQUIN    0.0      0.0    0.0    0.0

   Mayo  Junio  Julio  Agosto  Septiembre  Octubre  Noviembre  Diciembre
0   0.0    0.0    0.0     0.0         0.0      0.0        0.0        0.0
1   0.0    0.0    0.0     0.0         0.0      0.0        0.0        0.0
2   3.5    3.5    3.5     3.5         0.0      0.0        0.0        0.0
3   0.0    0.0    0.0     0.0         0.0      0.0        0.0        0.0
4   0.0    3.5    3.5     3.5         0.0      0.0        0.0        0.0

------------------------InformaciÃ³n general del DataFrame:------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1874 entries, 0 to 1873
Data columns (total 16 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   UBIGEO      1874 non-null   int64
 1   NOMBDEP     1874 non-null   object
 2   NOMBPROV    1874 non-null   object
 3   NOMBDIST    1874 non-null   object
 4   Enero       1874 non-null   float64
 5   Febrero     1874 non-null   float64
 6   Marzo       1874 non-null   float64
 7   Abril       1873 non-null   float64
 8   Mayo        1874 non-null   float64
 9   Junio       1874 non-null   float64
 10  Julio       1874 non-null   float64
 11  Agosto      1874 non-null   float64
 12  Septiembre  1873 non-null   float64
 13  Octubre     1874 non-null   float64
 14  Noviembre   1874 non-null   float64
 15  Diciembre   1874 non-null   float64
dtypes: float64(12), int64(1), object(3)
memory usage: 234.4+ KB

------------------------Conteo de valores nulos:------------------------
UBIGEO        0
NOMBDEP       0
NOMBPROV      0
NOMBDIST      0
Enero         0
Febrero       0
Marzo         0
Abril         1
Mayo          0
Junio         0
Julio         0
Agosto        0
Septiembre    1
Octubre       0
Noviembre     0
Diciembre     0
dtype: int64

------------------------Frecuencia de valores en una columna especÃ­fica:------------------------

In [22]:
def rellenar_nulos_con_promedio(df):
    # Obtener las columnas de los meses
    meses = [col for col in df.columns if col not in ['UBIGEO', 'NOMBDEP', 'NOMBPROV', 'NOMBDIST']]

    # Rellenar nulos con el promedio de los meses cercanos
    for i, mes in enumerate(meses):
        for index, row in df.iterrows():
            if pd.isnull(row[mes]):
                # Obtener meses anteriores y posteriores
                valores_vecinos = []
                if i > 0 and pd.notnull(row[meses[i - 1]]):  # Mes anterior
                    valores_vecinos.append(row[meses[i - 1]])
                if i < len(meses) - 1 and pd.notnull(row[meses[i + 1]]):  # Mes posterior
                    valores_vecinos.append(row[meses[i + 1]])

                # Calcular el promedio si hay valores vecinos
                if valores_vecinos:
                    df.at[index, mes] = sum(valores_vecinos) / len(valores_vecinos)

    return df

# Aplicar la funciÃ³n al DataFrame consolidado
df_consolidado_rellenado = rellenar_nulos_con_promedio(df_consolidado)

df_consolidado_rellenado

,UBIGEO,NOMBDEP,NOMBPROV,NOMBDIST,Enero,Febrero,Marzo,Abril,Mayo,Junio,Julio,Agosto,Septiembre,Octubre,Noviembre,Diciembre
0,10101,AMAZONAS,CHACHAPOYAS,CHACHAPOYAS,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,10102,AMAZONAS,CHACHAPOYAS,ASUNCION,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,10103,AMAZONAS,CHACHAPOYAS,BALSAS,0.0,0.0,0.0,0.0,3.5,3.5,3.5,3.5,0.0,0.0,0.0,0.0
3,10104,AMAZONAS,CHACHAPOYAS,CHETO,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,10105,AMAZONAS,CHACHAPOYAS,CHILIQUIN,0.0,0.0,0.0,0.0,0.0,3.5,3.5,3.5,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1869,250302,UCAYALI,PADRE ABAD,IRAZOLA,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1870,250303,UCAYALI,PADRE ABAD,CURIMANA,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1871,250304,UCAYALI,PADRE ABAD,NESHUYA,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1872,250305,UCAYALI,PADRE ABAD,ALEXANDER VON HUMBOLDT,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1873,250401,UCAYALI,PURUS,PURUS,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [23]:
# 1. Ver las primeras 5 filas
print("------------------------Primeras 5 filas:------------------------")
print(df_consolidado_rellenado.head())

# 3. Resumen general del DataFrame
print("\n------------------------InformaciÃ³n general del DataFrame:------------------------")
df_consolidado_rellenado.info()

# 7. Contar valores nulos por columna
print("\n------------------------Conteo de valores nulos:------------------------")
print(df_consolidado_rellenado.isnull().sum())
# 10. Contar frecuencia de valores en una columna (reemplazar 'COLUMNA' por el nombre de una columna)
print("\n------------------------Frecuencia de valores en una columna especÃ­fica:------------------------")
# print(df_consolidado_rellenado['PRODUCTO'].value_counts() if 'PRODUCTO' in df_consolidado_rellenado.columns else "La columna especificada no existe.")

------------------------Primeras 5 filas:------------------------
   UBIGEO   NOMBDEP     NOMBPROV     NOMBDIST  Enero  Febrero  Marzo  Abril  \
0   10101  AMAZONAS  CHACHAPOYAS  CHACHAPOYAS    0.0      0.0    0.0    0.0
1   10102  AMAZONAS  CHACHAPOYAS     ASUNCION    0.0      0.0    0.0    0.0
2   10103  AMAZONAS  CHACHAPOYAS       BALSAS    0.0      0.0    0.0    0.0
3   10104  AMAZONAS  CHACHAPOYAS        CHETO    0.0      0.0    0.0    0.0
4   10105  AMAZONAS  CHACHAPOYAS    CHILIQUIN    0.0      0.0    0.0    0.0

   Mayo  Junio  Julio  Agosto  Septiembre  Octubre  Noviembre  Diciembre
0   0.0    0.0    0.0     0.0         0.0      0.0        0.0        0.0
1   0.0    0.0    0.0     0.0         0.0      0.0        0.0        0.0
2   3.5    3.5    3.5     3.5         0.0      0.0        0.0        0.0
3   0.0    0.0    0.0     0.0         0.0      0.0        0.0        0.0
4   0.0    3.5    3.5     3.5         0.0      0.0        0.0        0.0

------------------------InformaciÃ³n general del DataFrame:------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1874 entries, 0 to 1873
Data columns (total 16 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   UBIGEO      1874 non-null   int64
 1   NOMBDEP     1874 non-null   object
 2   NOMBPROV    1874 non-null   object
 3   NOMBDIST    1874 non-null   object
 4   Enero       1874 non-null   float64
 5   Febrero     1874 non-null   float64
 6   Marzo       1874 non-null   float64
 7   Abril       1874 non-null   float64
 8   Mayo        1874 non-null   float64
 9   Junio       1874 non-null   float64
 10  Julio       1874 non-null   float64
 11  Agosto      1874 non-null   float64
 12  Septiembre  1874 non-null   float64
 13  Octubre     1874 non-null   float64
 14  Noviembre   1874 non-null   float64
 15  Diciembre   1874 non-null   float64
dtypes: float64(12), int64(1), object(3)
memory usage: 234.4+ KB

------------------------Conteo de valores nulos:------------------------
UBIGEO        0
NOMBDEP       0
NOMBPROV      0
NOMBDIST      0
Enero         0
Febrero       0
Marzo         0
Abril         0
Mayo          0
Junio         0
Julio         0
Agosto        0
Septiembre    0
Octubre       0
Noviembre     0
Diciembre     0
dtype: int64

------------------------Frecuencia de valores en una columna especÃ­fica:------------------------

In [24]:
# Especificar la ruta donde se guardarÃ¡ el archivo
ruta_salida = '/content/sample_data/consolidado_frecuencia_mensual.csv'

# Exportar el DataFrame a CSV
df_consolidado_rellenado.to_csv(ruta_salida, index=False)

print(f"El DataFrame consolidado se ha exportado correctamente a: {ruta_salida}")

El DataFrame consolidado se ha exportado correctamente a: /content/sample_data/consolidado_frecuencia_mensual.csv