# Precios de papa mensuales

Hay 3 tipos de precios:

- Promedio.
- Mínimo.
- Máximo.

Los datos extraídos pertenecen desde el año 2015 hasta el 2024, ver `Extraer_Precios.ipynb` si está interesado en ver como se extrajeron los datos.

Ahora para se crearon dos dataset para cada tipo, pues desde mayo de 2020, se dejó de tomar datos de la papa Perricholi.

In [11]:
import pandas as pd

### Precios promedios

In [12]:
# Cargar datos del precio máximo de la papa por mes
precios_max_papas_por_mes_pre202005 = pd.read_csv('precio_max_papas_por_mes_pre202005.csv')
precios_max_papas_por_mes_pre202005.head()

,Fecha,Papa Amarilla,Papa Blanca,Papa Canchan,Papa Color,Papa Huamantanga,Papa Huayro,Papa Negra Andina,Papa Perricholi,Papa Peruanita,Papa Unica,Papa Yungay
0,ENE-2015,3.0,2.15,2.5,2.35,2.2,2.0,2.40,2.0,2.6,2.20,2.30
1,FEB-2015,1.7,1.30,1.6,1.53,1.3,1.3,1.40,1.4,1.5,1.50,1.30
2,MAR-2015,2.2,1.45,1.4,1.33,1.5,1.5,1.40,1.4,1.5,1.40,1.50
3,ABR-2015,1.4,1.10,1.1,1.08,1.2,1.2,1.30,1.1,1.2,1.15,1.20
4,MAY-2015,1.6,0.78,0.9,0.85,1.1,1.1,0.95,0.8,1.0,0.90,0.85

In [13]:
precios_max_papas_por_mes_post202005 = pd.read_csv('precio_max_papas_por_mes_post202005.csv')
precios_max_papas_por_mes_post202005.head()

,Fecha,Papa Amarilla,Papa Blanca,Papa Canchan,Papa Color,Papa Huamantanga,Papa Huayro,Papa Negra Andina,Papa Peruanita,Papa Unica,Papa Yungay
0,JUN-2020,1.6,0.70,0.80,0.73,1.0,1.3,0.75,1.6,0.75,0.70
1,JUL-2020,2.3,0.60,0.70,0.70,1.4,1.5,0.80,1.6,0.70,0.60
2,AGO-2020,2.5,0.70,0.80,0.70,1.5,1.7,0.80,2.0,0.60,0.70
3,SEP-2020,2.8,0.70,0.65,0.60,2.0,2.2,0.80,2.2,0.55,0.70
4,OCT-2020,2.2,0.65,0.60,0.58,2.0,2.0,1.00,2.1,0.55,0.65

Concatenamos ambos

In [23]:
precios_max_papas_por_mes = pd.concat([precios_max_papas_por_mes_pre202005, precios_max_papas_por_mes_post202005], ignore_index=True)
precios_max_papas_por_mes.to_csv('completo/precio_max_papas_por_mes.csv', index=False)

### Precios mínimos

In [15]:
# Cargar datos del precio mínimo de la papa por mes
precios_min_papas_por_mes_pre202005 = pd.read_csv('precio_min_papas_por_mes_pre202005.csv')
precios_min_papas_por_mes_pre202005.head()

,Fecha,Papa Amarilla,Papa Blanca,Papa Canchan,Papa Color,Papa Huamantanga,Papa Huayro,Papa Negra Andina,Papa Perricholi,Papa Peruanita,Papa Unica,Papa Yungay
0,ENE-2015,1.1,0.80,1.10,1.05,0.70,1.00,0.90,0.80,1.1,1.00,0.70
1,FEB-2015,1.4,1.03,1.30,1.25,0.90,0.90,1.00,1.10,1.1,1.20,0.85
2,MAR-2015,1.4,0.98,1.00,1.00,0.90,0.90,0.95,0.90,1.1,0.90,0.95
3,ABR-2015,0.9,0.60,0.70,0.65,0.95,0.65,0.70,0.55,0.8,0.55,0.60
4,MAY-2015,1.0,0.55,0.65,0.65,0.85,0.75,0.70,0.50,0.7,0.60,0.60

In [16]:
precios_min_papas_por_mes_post202005 = pd.read_csv('precio_min_papas_por_mes_post202005.csv')
precios_min_papas_por_mes_post202005.head()

,Fecha,Papa Amarilla,Papa Blanca,Papa Canchan,Papa Color,Papa Huamantanga,Papa Huayro,Papa Negra Andina,Papa Peruanita,Papa Unica,Papa Yungay
0,JUN-2020,1.0,0.35,0.50,0.50,0.7,0.85,0.50,0.9,0.45,0.35
1,JUL-2020,1.4,0.40,0.50,0.45,0.9,1.00,0.50,1.1,0.40,0.40
2,AGO-2020,1.8,0.40,0.50,0.45,1.1,1.30,0.65,1.3,0.35,0.40
3,SEP-2020,2.0,0.40,0.50,0.40,1.2,1.50,0.60,1.7,0.30,0.40
4,OCT-2020,1.5,0.40,0.35,0.33,1.4,1.70,0.70,1.5,0.30,0.40

Concatenamos

In [22]:
precios_min_papas_por_mes = pd.concat([precios_min_papas_por_mes_pre202005, precios_min_papas_por_mes_post202005], ignore_index=True)
precios_min_papas_por_mes.to_csv('completo/precio_min_papas_por_mes.csv', index=False)

### Precios promedios

In [17]:
# Cargar datos del precio promedio de la papa por mes
precios_prom_papas_por_mes_pre202005 = pd.read_csv('precio_prom_papas_por_mes_pre202005.csv')
precios_prom_papas_por_mes_pre202005.head()

,Fecha,Papa Amarilla,Papa Blanca,Papa Canchan,Papa Color,Papa Huamantanga,Papa Huayro,Papa Negra Andina,Papa Perricholi,Papa Peruanita,Papa Unica,Papa Yungay
0,ENE-2015,1.72,1.03,1.33,1.31,1.17,1.28,1.09,1.10,1.63,1.23,0.95
1,FEB-2015,1.52,1.15,1.46,1.39,1.06,1.06,1.15,1.25,1.35,1.41,0.99
2,MAR-2015,1.64,1.12,1.18,1.18,1.13,1.13,1.03,1.05,1.29,1.19,1.23
3,ABR-2015,1.16,0.82,0.90,0.85,1.08,0.89,1.06,0.77,0.95,0.76,0.82
4,MAY-2015,1.23,0.64,0.81,0.78,1.02,0.90,0.84,0.61,0.83,0.73,0.69

In [18]:
precios_prom_papas_por_mes_post202005 = pd.read_csv('precio_prom_papas_por_mes_post202005.csv')
precios_prom_papas_por_mes_post202005.head()

,Fecha,Papa Amarilla,Papa Blanca,Papa Canchan,Papa Color,Papa Huamantanga,Papa Huayro,Papa Negra Andina,Papa Peruanita,Papa Unica,Papa Yungay
0,JUN-2020,1.23,0.53,0.62,0.60,0.90,0.99,0.67,1.18,0.58,0.52
1,JUL-2020,1.82,0.48,0.61,0.59,1.19,1.21,0.68,1.40,0.56,0.49
2,AGO-2020,2.21,0.54,0.66,0.57,1.36,1.53,0.71,1.69,0.48,0.54
3,SEP-2020,2.24,0.59,0.55,0.48,1.33,1.75,0.71,1.93,0.40,0.59
4,OCT-2020,1.83,0.55,0.49,0.46,1.63,1.92,0.85,1.70,0.42,0.55

In [24]:
precios_prom_papas_por_mes = pd.concat([precios_prom_papas_por_mes_pre202005, precios_prom_papas_por_mes_post202005], ignore_index=True)
precios_prom_papas_por_mes.to_csv('completo/precio_prom_papas_por_mes.csv', index=False)